name: TokoToko
options:
  bundleIdPrefix: com.RRRRRRR777
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: "16.1"
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 2
  tabWidth: 2

fileGroups:
  - README.md
  - project.yml
  - .swiftlint.yml
  - CLAUDE.md
  - .gitignore
  - buildServer.json
  - firebase.json
  - firestore.indexes.json
  - firestore.rules
  - storage.rules
  - Info.plist
  - ci_scripts
  - .claude

targetTemplates:
  CommonSettings:
    settings:
      base:
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 11.0.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 8.0.0
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector.git
    from: 0.10.0
targets:
  TokoToko:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    supportedDestinations: [iOS]
    sources:
      - path: TokoToko
        excludes:
          - "Preview Content"
    resources:
      - path: TokoToko/Preview Content
      - path: TokoToko/Assets.xcassets
      - path: TokoToko/GoogleService-Info.plist
      - path: Documentation.docc
    templates: [CommonSettings]
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
      - package: GoogleSignIn
        product: GoogleSignIn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.RRRRRRR777.TokoToko
        INFOPLIST_KEY_CFBundleDisplayName: "とことこ"
        INFOPLIST_KEY_CFBundleName: "とことこ - お散歩SNS"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "このアプリはあなたの現在地を表示するために位置情報を使用します。"
        INFOPLIST_KEY_NSLocationAlwaysAndWhenInUseUsageDescription: "このアプリはバックグラウンドでも位置情報を追跡するために位置情報を使用します。"
        INFOPLIST_KEY_NSLocationAlwaysUsageDescription: "このアプリはバックグラウンドでも位置情報を追跡するために位置情報を使用します。"
        INFOPLIST_KEY_NSMotionUsageDescription: "このアプリは散歩中の歩数を正確に記録するためにモーションセンサーを使用します。"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1"
        DOCC_CATALOG_IDENTIFIER: com.RRRRRRR777.TokoToko
        DOCC_EXTRACT_OBJC_INFO_FOR_SWIFT_SYMBOLS: YES
        DOCC_HOSTING_BASE_PATH: TokoToko
    info:
      path: Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLSchemes:
              - com.googleusercontent.apps.730739320416-rjs5ngp3np3b4d8hd4fmn4c6o05ppoek
        UIBackgroundModes:
          - location
        ITSAppUsesNonExemptEncryption: false
    scheme:
      testTargets:
        - TokoTokoTests
        - TokoTokoUITests

  TokoTokoTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    supportedDestinations: [iOS]
    sources:
      - path: TokoTokoTests
    templates: [CommonSettings]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.RRRRRRR777.TokoTokoTests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - target: TokoToko
      - package: ViewInspector
        product: ViewInspector

  TokoTokoUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    supportedDestinations: [iOS]
    sources:
      - path: TokoTokoUITests
    templates: [CommonSettings]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.RRRRRRR777.TokoTokoUITests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - target: TokoToko
      - package: ViewInspector
        product: ViewInspector
