name: TokoToko
options:
  bundleIdPrefix: com.RRRRRRR777
  deploymentTarget:
    iOS: 18.1
  xcodeVersion: "16.1"
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 2
  tabWidth: 2

include:
  - path: .env
    relativePaths: true
    optional: true

targetTemplates:
  CommonSettings:
    settings:
      base:
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 11.0.0
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector.git
    from: 0.10.0
targets:
  TokoToko:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 18.1
    sources:
      - path: TokoToko
        excludes:
          - "Preview Content"
    resources:
      - path: TokoToko/Preview Content
      - path: TokoToko/Assets.xcassets
    templates: [CommonSettings]
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.RRRRRRR777.TokoToko
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "このアプリはあなたの現在地を表示するために位置情報を使用します。"
        INFOPLIST_KEY_NSLocationAlwaysAndWhenInUseUsageDescription: "このアプリはバックグラウンドでも位置情報を追跡するために位置情報を使用します。"
        INFOPLIST_KEY_NSLocationAlwaysUsageDescription: "このアプリはバックグラウンドでも位置情報を追跡するために位置情報を使用します。"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        UIBackgroundModes: ["location"]
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
    scheme:
      testTargets:
        - TokoTokoTests
        - TokoTokoUITests

  TokoTokoTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget:
      iOS: 18.1
    sources:
      - path: TokoTokoTests
    templates: [CommonSettings]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.RRRRRRR777.TokoTokoTests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - target: TokoToko

  TokoTokoUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget:
      iOS: 18.1
    sources:
      - path: TokoTokoUITests
    templates: [CommonSettings]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.RRRRRRR777.TokoTokoUITests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - target: TokoToko
      - package: ViewInspector
        product: ViewInspector
