name: Swift Format & Lint

on:
  push:
    branches:
      - main
      - dev-*
  pull_request:

jobs:
  format-lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.9'

      - name: Install SwiftFormat
        run: |
          git clone https://github.com/nicklockwood/SwiftFormat.git
          cd SwiftFormat
          swift build -c release
          cp .build/release/swiftformat /usr/local/bin/

      - name: Install SwiftLint
        run: |
          curl -L -O https://github.com/realm/SwiftLint/releases/download/0.54.0/swiftlint_linux.zip
          unzip swiftlint_linux.zip
          sudo mv swiftlint /usr/local/bin

      - name: Get changed Swift files
        id: changed-files
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref || 'main' }}"
          git fetch origin $BASE_BRANCH
          FILES=$(git diff --name-only origin/$BASE_BRANCH...HEAD -- '*.swift')
          echo "CHANGED_FILES=$FILES" >> $GITHUB_ENV

      - name: Run SwiftFormat (Lint Mode)
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            echo "$CHANGED_FILES" | xargs swiftformat --lint
          else
            echo "No Swift files changed."
          fi

      - name: Run SwiftLint (only on changed files)
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            echo "$CHANGED_FILES" | xargs -n 1 swiftlint lint --path
          else
            echo "No Swift files changed."
          fi

