name: Xcode Build & Test

on:
  pull_request:
    branches:
      - main

jobs:
  xcodebuild-test:
    runs-on: bokuyamada

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DEVELOPMENT_TEAM=${{ secrets.DEVELOPMENT_TEAM }}" >> .env

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen

      - name: Cache Swift Package dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies \
            -project TokoToko.xcodeproj

      - name: Build & Run Tests
        run: |
          xcodebuild test \
            -project TokoToko.xcodeproj \
            -scheme TokoToko \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1' \
            -resultBundlePath TestResults

      - name: Upload Test Results (optional)
        uses: actions/upload-artifact@v4
        with:
          name: xcode-test-results
          path: TestResults
